/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tommymangia.fakezone_grafica;

/**
 *
 * @author tommaso
 */
public class MainForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForm.class.getName());

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenuUscita = new javax.swing.JMenuItem();
        gestioneMenu = new javax.swing.JMenu();
        gestioneMenuClienti = new javax.swing.JMenuItem();
        gestioneMenuProdotti = new javax.swing.JMenuItem();
        gestioneMenuOrdini = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fakezone");

        fileMenu.setText("File");

        fileMenuUscita.setText("Uscita");
        fileMenuUscita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fileMenuUscitaMousePressed(evt);
            }
        });
        fileMenuUscita.addActionListener(this::fileMenuUscitaActionPerformed);
        fileMenu.add(fileMenuUscita);

        jMenuBar1.add(fileMenu);

        gestioneMenu.setText("Gestione");

        gestioneMenuClienti.setText("Clienti");
        gestioneMenu.add(gestioneMenuClienti);

        gestioneMenuProdotti.setText("Prodotti");
        gestioneMenu.add(gestioneMenuProdotti);

        gestioneMenuOrdini.setText("Ordini");
        gestioneMenu.add(gestioneMenuOrdini);

        jMenuBar1.add(gestioneMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuUscitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuUscitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuUscitaActionPerformed

    private void fileMenuUscitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuUscitaMousePressed
        System.exit(0);
    }//GEN-LAST:event_fileMenuUscitaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenuUscita;
    private javax.swing.JMenu gestioneMenu;
    private javax.swing.JMenuItem gestioneMenuClienti;
    private javax.swing.JMenuItem gestioneMenuOrdini;
    private javax.swing.JMenuItem gestioneMenuProdotti;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
