/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tommymangia.gestione_scuola;

/**
 *
 * @author tommaso
 */
public class mainForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainForm.class.getName());

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuBarFileMenu = new javax.swing.JMenu();
        menuFileExit = new javax.swing.JMenuItem();
        menuBarEditorMenu = new javax.swing.JMenu();
        menuBarEditorClassi = new javax.swing.JMenuItem();
        menuBarEditorDocenti = new javax.swing.JMenuItem();
        menuBarEditorStudenti = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestione Scuola");

        menuBarFileMenu.setText("File");

        menuFileExit.setText("Esci");
        menuFileExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuFileExitMousePressed(evt);
            }
        });
        menuFileExit.addActionListener(this::menuFileExitActionPerformed);
        menuBarFileMenu.add(menuFileExit);

        jMenuBar1.add(menuBarFileMenu);

        menuBarEditorMenu.setText("Editor");

        menuBarEditorClassi.setLabel("Classi");
        menuBarEditorClassi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBarEditorClassiMousePressed(evt);
            }
        });
        menuBarEditorMenu.add(menuBarEditorClassi);

        menuBarEditorDocenti.setLabel("Docenti");
        menuBarEditorMenu.add(menuBarEditorDocenti);

        menuBarEditorStudenti.setLabel("Studenti");
        menuBarEditorMenu.add(menuBarEditorStudenti);

        jMenuBar1.add(menuBarEditorMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileExitActionPerformed

    private void menuFileExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_menuFileExitMousePressed

    private void menuBarEditorClassiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarEditorClassiMousePressed
        classiForm formClassi = new classiForm();
        formClassi.setVisible(true);
    }//GEN-LAST:event_menuBarEditorClassiMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBarEditorClassi;
    private javax.swing.JMenuItem menuBarEditorDocenti;
    private javax.swing.JMenu menuBarEditorMenu;
    private javax.swing.JMenuItem menuBarEditorStudenti;
    private javax.swing.JMenu menuBarFileMenu;
    private javax.swing.JMenuItem menuFileExit;
    // End of variables declaration//GEN-END:variables
}
